Tracta TypeError en base64.b64encode()
UPC/mailtoticket pull request #215
Opened 2021-07-07 12:28 UTC by aaguilera

Tracta l'excepció TypeError en codificar un attachment que és detectat
com un string i no com una seqüència de bytes (bytes-like).

Fixes #184

2021-07-08 13:19 UTC, alexm requested changes
El commit log diu fixes #184, que entenc que no té res a veure. Hauria de ser 214, oi?

Pots corregir-ho perquè no generi confusió?

2021-07-08 13:21 UTC, alexm requested changes
Podries eliminar el commit buit? Entenc que fos necessari inicialment per disparar el build, però no crec que calgui integrar-lo al codi principal.

2021-07-09 06:09 UTC, aaguilera commented
OK. He eliminat el commit buit, i he editat el missatge del commit.
No sé si ho he fet bé (he fet un `rebase -i`, i després un `push --force`, que no sé si és gaire ortodox).

2021-07-09 07:33 UTC, alexm commented
> OK. He eliminat el commit buit, i he editat el missatge del commit.
> No sé si ho he fet bé (he fet un `rebase -i`, i després un `push --force`, que no sé si és gaire ortodox).

És el que s'havia de fer. Jo prefereixo utilitzar `--force-with-lease` perquè t'avisa si algú altre ha fet canvis a la branca remota, però en aquest cas ja està bé perquè ningú més havia fet cap canvi.

El que no sé si has vist és que hi ha un canvi addicional, el del README amb la nova imatge de Travis, que prové del PR que vaig integrar ahir. Has sincronitzat la teva master amb el remot abans de fer el rebase? Si ho fas diria que el commit extra desapareixerà.

2021-07-09 07:40 UTC, alexm commented
Com que acabo d'integrar la #218, ara aquesta branca té conflictes. Aprofitant que cal resoldre'ls, jo m'asseguraria que els canvis es basen en la darrera versió de master.

2021-07-09 08:29 UTC, aaguilera commented
Fet. Conflicte resolt.

2021-07-09 08:40 UTC, alexm approved these changes

2021-07-09 08:40 UTC, merged

2021-07-09 08:40 UTC, alexm commented
Bona feina!